### ISSUE TITLE
License Choice?

### ISSUE THREAD

**Issue by apiep** [qiscus/qiscus-sdk-web#1]
Nganu, karena sdk untuk web belum ada lisensi, jadi lisensi mana yang akan digunakan? 😁
Sebagai pertimbangan, untuk ios sudah ada MIT kan https://github.com/qiscus/qiscus-sdk-ios/blob/feature/chatUI/LICENSE

**Comment by desertlion** [comment]
Kita bisa menggunakan license "nganu-pl", intinya bebas nganu.

**Comment by asharijuang** [comment]
nganu-pl ki devinisi pie jal :runner:
