### ISSUE TITLE
Change endpoint protocol to https:// instead of //

### ISSUE THREAD

**Issue by apiep** [qiscus/qiscus-sdk-web#12]
We need to force the endpoint to use `https://` instead of `//` so it can be used on cordova that only served in `file://` protocol.

**Comment by desertlion** [comment]
Bukannya sudah di force https semua bro, aq ga liat ada file lain yang masih pake '//'

**Comment by apiep** [comment]
Hmm iya, tp kok bisa pakai `file://` padahal sudah di force ke `https://` :/

**Comment by desertlion** [comment]
Orangnya keliru cara manggil file nya aja mungkin, lagipula dari screenshot yang dipanggil file auto-init.html,padahal file itu ga dipake
